import { Bot, Info, Volume2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/misc'
import { cn, titleCase } from '@/lib/utils'
import type { PublicQuestion } from '@/types'

export function QuestionCard({ q, speaking, onRepeat, canSpeak }: { q: PublicQuestion; speaking?: boolean; onRepeat?: () => void; canSpeak?: boolean }) {
  return (
    <Card>
      <CardContent className="pt-5">
        <div className="flex items-start gap-4">
          <div className={cn('relative grid size-11 shrink-0 place-items-center rounded-full bg-gradient-to-br from-brand-600 to-accent-500 text-white', speaking && 'ring-4 ring-brand-200')}>
            <Bot className="size-5" aria-hidden />
            {speaking && <span className="absolute inset-0 animate-ping rounded-full bg-brand-400/30" aria-hidden />}
          </div>
          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-xs font-medium text-ink-500">AI interviewer · Question {q.sequence_no}</span>
              <Badge>{q.topic}</Badge>
              <Badge tone="violet">{titleCase(q.kind)}</Badge>
              <Badge tone="neutral">Difficulty {q.difficulty}/5</Badge>
              {q.is_follow_up && <Badge tone="warning">Follow-up</Badge>}
            </div>
            <p className="mt-3 whitespace-pre-line text-[1.05rem] font-medium leading-relaxed text-ink-900" aria-live="polite">
              {q.question_text}
            </p>

            {q.details?.function_signature && (
              <pre className="mt-4 overflow-x-auto rounded-lg bg-slate-900 p-3 font-mono text-sm text-slate-100">{q.details.function_signature}</pre>
            )}
            {q.details?.examples && q.details.examples.length > 0 && (
              <div className="mt-4 space-y-2">
                {q.details.examples.map((ex, i) => (
                  <div key={i} className="rounded-lg border border-line bg-slate-50 p-3 font-mono text-xs">
                    <p>
                      <span className="text-ink-400">Input:</span> {ex.input}
                    </p>
                    <p>
                      <span className="text-ink-400">Output:</span> {ex.output}
                    </p>
                    {ex.explanation && <p className="mt-1 font-sans text-ink-500">{ex.explanation}</p>}
                  </div>
                ))}
              </div>
            )}
            {q.details?.constraints && q.details.constraints.length > 0 && (
              <ul className="mt-3 list-disc pl-5 text-sm text-ink-700">
                {q.details.constraints.map((c, i) => (
                  <li key={i}>{c}</li>
                ))}
              </ul>
            )}

            <div className="mt-4 flex flex-wrap items-center gap-3">
              {canSpeak && onRepeat && (
                <Button type="button" variant="ghost" size="sm" onClick={onRepeat}>
                  <Volume2 /> Repeat question
                </Button>
              )}
              <details className="text-xs text-ink-500">
                <summary className="inline-flex cursor-pointer items-center gap-1">
                  <Info className="size-3.5" aria-hidden /> Why this question?
                </summary>
                <p className="mt-1 max-w-xl">
                  {q.selection_reason} {q.source === 'ai_generated' ? 'Generated by AI for practice; not an official company question.' : ''}
                </p>
              </details>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
